// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDTD1cm8tSJBbgBJSYjmjD7H3_FUXgT0',
    appId: '1:893881193388:web:561e82acd8fea008802009',
    messagingSenderId: '893881193388',
    projectId: 'plantix-1c7f4',
    authDomain: 'plantix-1c7f4.firebaseapp.com',
    storageBucket: 'plantix-1c7f4.appspot.com',
    measurementId: 'G-R0BND9T1V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQg4Wbo_VaCzLyurPcvqYrYZJ-Sg1gjKk',
    appId: '1:893881193388:android:0a27178e82173df0802009',
    messagingSenderId: '893881193388',
    projectId: 'plantix-1c7f4',
    storageBucket: 'plantix-1c7f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9k_nQEH1qrOPddj9vetvRKH7Keysth3g',
    appId: '1:893881193388:ios:3c7258345bff99d0802009',
    messagingSenderId: '893881193388',
    projectId: 'plantix-1c7f4',
    storageBucket: 'plantix-1c7f4.appspot.com',
    iosClientId: '893881193388-1gcl0hp6rpdspib2f8ic3ndg424nqhng.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9k_nQEH1qrOPddj9vetvRKH7Keysth3g',
    appId: '1:893881193388:ios:e120920dceee6da3802009',
    messagingSenderId: '893881193388',
    projectId: 'plantix-1c7f4',
    storageBucket: 'plantix-1c7f4.appspot.com',
    iosClientId: '893881193388-7aj2bs6k1d76dn5jo4dt2rau1ta4lr9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.testing.RunnerTests',
  );
}
